admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

JAMNotasBackendBundle:
    resource: "@JAMNotasBackendBundle/Resources/config/routing.yml"
    prefix:   /

JAMNotasFrontendBundle:
    resource: "@JAMNotasFrontendBundle/Resources/config/routing.yml"
    prefix:   /notas

JAMAlimentosBundle:
    resource: "@JazzywebAulasMentorAlimentosBundle/Resources/config/routing.yml"
    prefix:   /alimentos
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
