parameters:
    jam_notas_frontend.registro.class: Jazzyweb\AulasMentor\NotasFrontendBundle\Services\Registro
    jam_notas_frontend.pago.class: Jazzyweb\AulasMentor\NotasFrontendBundle\Services\Pago

services:
    jam_notas_frontend.registro:
        class: %jam_notas_frontend.registro.class%
        arguments:
         - "@doctrine"
         - "@mailer"
         - "@templating"
         - "@security.encoder_factory"
    jam_notas_frontend.pago:
        class: %jam_notas_frontend.pago.class%
        arguments:
         - "@doctrine"
         - "@mailer"
         - "@templating"
         - "@security.encoder_factory"     