<?php

namespace Jazzyweb\AulasMentor\AlimentosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * alimentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alimentosRepository extends EntityRepository
{
}