<?php

namespace Jazzyweb\AulasMentor\NotasFrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtiquetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtiquetaRepository extends EntityRepository {

    public function findByUsuarioOrderedByTexto($username) {
        $query = $this->getEntityManager()->createQuery(
                        "SELECT e FROM JAMNotasFrontendBundle:Etiqueta e
                      JOIN  e.usuario u where u.id = :username ORDER BY e.texto ASC")
                ->setParameters(array('username' => $username));

        return $query->getResult();
    }

    public function findOneByTextoAndUsuario($tag, $usuario) {
        $query = $this->getEntityManager()->createQuery(
                        "SELECT e FROM JAMNotasFrontendBundle:Etiqueta e
                      JOIN  e.usuario u where u.id = :userid 
                      AND e.texto = :tag
                        ORDER BY e.texto ASC")
                ->setParameters(array('userid' => $usuario->getId(), 'tag' => $tag,));

        $result = $query->getResult();
        if (count($result) > 0) {
            return $result[0];
        }else{
            return null;
        }        
    }

}